### ISSUE TITLE
Bug: Query View - Copy issues

### ISSUE THREAD

**Issue by darrylthom** [luusluus/vscode-parquet-visualizer#100]
So the overall formatting change worked, however, I have some columns that are Strings but numbers without leading zeroes. Is there a way to make the format respect the data types that DuckDB is identifying the column as, and then do the according mso tag?

Example
5000 (but String) should be formatting as mso @? Right now it is converting it to a number even though **internally** this is text (albeit numeric-looking).

Also, dates like 2024-01-01 are also being converted to Text (mso @), but should instead of an mso for date applied like: mso-number-format:"yyyy-mm-dd"

Maybe this needs to be approached from the true returned data type rather than a regex approach

**Comment by luusluus** [comment]
Makes sense. Should be doable

**Comment by luusluus** [comment]
Changes here https://github.com/luusluus/vscode-parquet-visualizer/pull/108

**Comment by luusluus** [comment]
It's in the new release, you can test it.

**Comment by darrylthom** [comment]
This is working now, great work
