### ISSUE TITLE
Bug: Disable Excel export for windows

### ISSUE THREAD

**Issue by luusluus** [luusluus/vscode-parquet-visualizer#103]
Related to issue

https://github.com/luusluus/vscode-parquet-visualizer/issues/99

**Comment by luusluus** [comment]
Changes in #104

**Comment by darrylthom** [comment]
Posted an update here where I managed to get it working with a workaround:

https://github.com/luusluus/vscode-parquet-visualizer/issues/99#issuecomment-2509524551
