### ISSUE TITLE
Bug: Critical - All parquet files no longer opening on Windows (missing output\duckdb.node)

### ISSUE THREAD

**Issue by darrylthom** [luusluus/vscode-parquet-visualizer#111]
On Windows it gets stuck when opening all parquet files now:

![image](https://github.com/user-attachments/assets/3802600c-59b3-43dc-a184-31eb9bdd29b7)

**\binding\duckdb.node** is missing in the output folder

2024-12-01 09:22:22.296 [error] Activating extension lucien-martijn.parquet-visualizer failed due to an error:
2024-12-01 09:22:22.296 [error] Error: Cannot find module 'c:\Users\12042\.vscode\extensions\lucien-martijn.parquet-visualizer-0.16.0-win32-x64\out\binding\duckdb.node'

**Comment by luusluus** [comment]
Oof, will fix today asap.

**Comment by luusluus** [comment]
I will focus on enabling pre-releases as well.  And test without node modules going forward.

**Comment by darrylthom** [comment]
No worries, I have been bombarding you with requests, so some new issues are bound to happen, it's understandable

**Comment by luusluus** [comment]
It's the same or all OS's

**Comment by luusluus** [comment]
Should be fixed now. Installed latest version, and tested on windows and linux.
