### ISSUE TITLE
Feature: Recall last Export folder

### ISSUE THREAD

**Issue by darrylthom** [luusluus/vscode-parquet-visualizer#112]
When exporting a file to a location, have it capture the folder and file name last used.

Next time, rather than defaulting to the folder the file is located in, default it to the last folder and file name you used. If the folder no longer exists, default to the original file location folder.

This is handy since I tend to be exporting multiple results and it is painful to have to navigate back to the intended output folder each time.

**Comment by luusluus** [comment]
I have looked at this, but I don't think the vscode api supports this, but I'll investigate more. I could maybe make the default location configurable

**Comment by luusluus** [comment]
I can save the last export folder within one "session". A session means the duration of an opened editor. When we close the editor, we'll lose that information.

**Comment by darrylthom** [comment]
One session would still be a big upgrade

**Comment by luusluus** [comment]
I'll prioritize this.

**Comment by darrylthom** [comment]
> I can save the last export folder within one "session". A session means the duration of an opened editor. When we close the editor, we'll lose that information.

Is it possible to save the last export folder to a variable that is reloaded next time you open VSCode? The post mentions state mementos:
https://stackoverflow.com/questions/51821924/how-to-persist-information-for-a-vscode-extension

**Comment by darrylthom** [comment]
> Thank you, that can help. I can't help but wonder how to store the state for each opened parquet file?
> 
> I'll store it as default location for now. But we can also use vscode configuration API for that.

I suppose another useful one would be for it to remember your last selected Page Size (as long as the array hasn't changed where your last selection is no longer available in the dropdown)

**Comment by luusluus** [comment]
I've merged the recall in memory for now. Can you create a new issue where you describe above? where it persists between vscode reloads.

**Comment by darrylthom** [comment]
> I've merged the recall in memory for now. Can you create a new issue where you describe above? where it persists between vscode reloads?

Sure thing -- done! It looks like your latest change works where it remembers the path in current session, but I don't think the Open folder feature got added to this one.

**Comment by luusluus** [comment]
Correct, the PR is still open and under development :)
