### ISSUE TITLE
Feature: After exporting, add "Display file" button/link to the VSCode toast

### ISSUE THREAD

**Issue by darrylthom** [luusluus/vscode-parquet-visualizer#113]
When clicking this new "Display file" button/link, have Windows Explorer pop up to that file location with the file itself being selected, similar to this:

![image](https://github.com/user-attachments/assets/eb562ecd-3958-4504-af5b-bd0b248baac8)

**Comment by luusluus** [comment]
Sorry, I don't understand this feature. What is the "display file" button/link. Is that a windows feature?

**Comment by darrylthom** [comment]
On the window that pops up saying export successful, I think it’s possible to make a link or button on it that shows you the folder it got exported to so you can quickly open it.

Something like this (from ChatGPT):

`const vscode = require('vscode');
const path = require('path');

function exportFile() {
    // Simulate the export process and define the export folder path
    const exportFolderPath = path.join(vscode.workspace.workspaceFolders[0].uri.fsPath, 'exports');

    // Create the export folder if it doesn't exist
    if (!fs.existsSync(exportFolderPath)) {
        fs.mkdirSync(exportFolderPath, { recursive: true });
    }

    // Simulate a file export
    const exportedFilePath = path.join(exportFolderPath, 'exportedFile.txt');
    fs.writeFileSync(exportedFilePath, 'Exported content');

    // Show a toast notification with an option to open the folder
    vscode.window.showInformationMessage('File exported successfully!', 'Open Folder').then((selection) => {
        if (selection === 'Open Folder') {
            // Open the folder in the system's file explorer
            const folderUri = vscode.Uri.file(exportFolderPath);
            vscode.commands.executeCommand('revealFileInOS', folderUri);
        }
    });
}

function activate(context) {
    let disposable = vscode.commands.registerCommand('extension.exportFile', exportFile);
    context.subscriptions.push(disposable);
}

function deactivate() {}

module.exports = {
    activate,
    deactivate
}; `

**Comment by darrylthom** [comment]
It would work similar to this:

![image](https://github.com/user-attachments/assets/e8ef129a-34c9-4801-886e-0acf820415b1)

**Comment by darrylthom** [comment]
This one isn’t in the new version I don’t think.

**Comment by luusluus** [comment]
Correct, it isn't yet.

**Comment by luusluus** [comment]
Should be supported for windows, and wsl. Untested for macos or linux.
