### ISSUE TITLE
Bug: Query View - Autocomplete not working for column names with spaces

### ISSUE THREAD

**Issue by darrylthom** [luusluus/vscode-parquet-visualizer#130]
Let's imagine I am writing: SELECT * FROM data WHERE "Column Test" = 2

When I am typing and the column name **Column Test** comes up in autocomplete suggestions, once selected I will get

SELECT * FROM data WHERE **Column Test** (which won't work without the quotes)

Rather than **"Column Test"**

![image](https://github.com/user-attachments/assets/832441c4-450e-44c9-80aa-8a613cf3df0a)

![image](https://github.com/user-attachments/assets/760fa783-cfd5-4b9f-8517-d991177b2d80)

[spaced column.zip](https://github.com/user-attachments/files/18130169/spaced.column.zip)

**Comment by luusluus** [comment]
Fix is in [this release](https://github.com/luusluus/vscode-parquet-visualizer/releases/tag/v0.19.0).

**Comment by darrylthom** [comment]
Working great now.
