### ISSUE TITLE
Bug: Data and Query Views - Amperstands are encoded in tooltips

### ISSUE THREAD

**Issue by darrylthom** [luusluus/vscode-parquet-visualizer#131]
![image](https://github.com/user-attachments/assets/100d1f81-d29b-4b24-b40f-c7aebf8b91f5)
[amperstand string.zip](https://github.com/user-attachments/files/18130373/amperstand.string.zip)

My use case is that for some processes I save file paths as a column to my dataset, and some of these include things such as P&L in the folder names. Then when I am copying it from the tooltip and pasting it into explorer, I have to manually change amp to & otherwise it won't find the file.

**Comment by luusluus** [comment]
The ampersand is indeed escaped currently. There was a previous issue where a user had HTML in it's values. Now I simply escape all &, <, >, ", and ' characters.

**Comment by darrylthom** [comment]
Is there a way to make them still display properly even when escaped like that?

**Comment by luusluus** [comment]
I've added a piece of code that checks whether the text is HTML, before I escape it.

**Comment by darrylthom** [comment]
> I've added a piece of code that checks whether the text is HTML, before I escape it.

Thanks for this, also congrats on hitting 10K+ downloads!

**Comment by luusluus** [comment]
> > I've added a piece of code that checks whether the text is HTML, before I escape it.
> 
> 
> 
> Thanks for this, also congrats on hitting 10K+ downloads!

Thank you! You are now also part of that success.

**Comment by luusluus** [comment]
Fix is in [this release](https://github.com/luusluus/vscode-parquet-visualizer/releases/tag/v0.19.0).

**Comment by darrylthom** [comment]
This is working.
