### ISSUE TITLE
Bug: Export XLSX randomly failing

### ISSUE THREAD

**Issue by darrylthom** [luusluus/vscode-parquet-visualizer#137]
Receiving the error message:
Export failed: Invalid Error: Unknown exception in Finalize!

CSV is fine and the new show in folder works good.

**Comment by luusluus** [comment]
Is this since the new release?

**Comment by darrylthom** [comment]
It happened sometimes with the previous as well. I'll try to dig into it more later this week, but possibly a race condition for writing/renaming.

**Comment by luusluus** [comment]
Let me try to reproduce it.

**Comment by luusluus** [comment]
I have not been able to reproduce this. Can you provide the parquet file on which this fails?

**Comment by darrylthom** [comment]
I haven’t been able to reproduce this, we can close it off and I will reopen if I can figure out a reproducible example.
