### ISSUE TITLE
Bug: Export recommended file extension should reflect export extension selected

### ISSUE THREAD

**Issue by darrylthom** [luusluus/vscode-parquet-visualizer#138]
For example, when I export as an XLSX, and then immediately try exporting as a CSV, it is giving "Export.xlsx" as my recommended file name even though it should be .CSV. Perhaps override the extension at the end depending on the selection made (regex?)

Probably has to do with the new recall feature, just needs that small tweak to make it perfect.

**Comment by luusluus** [comment]
fix released here: https://github.com/luusluus/vscode-parquet-visualizer/releases/tag/v0.19.0

**Comment by darrylthom** [comment]
Good now.
