### ISSUE TITLE
Critical Bug: Assertion Failed: argument is undefined or null

### ISSUE THREAD

**Issue by darrylthom** [luusluus/vscode-parquet-visualizer#144]
Cannot open any parquet files without experiencing this error message.

The editor could not be opened due to an unexpected error: Assertion Failed: argument is undefined or null

Related to my settings.json file not having the page size numbers wrapped in double quotes. Only happens if you have edited settings.json previously. Maybe if there is an error with settings, it can reset to default?

**Comment by luusluus** [comment]
Reproduced. Indeed, if you had settings that had an array with numbers instead of strings, then this will break. 
Actually, this is a breaking change. I'll produce a hot fix now.

**Comment by luusluus** [comment]
In any case, the `defaultPageSizes` should now contain numbers wrapped in double quotes and or the "all" value.

**Comment by darrylthom** [comment]
This is working now as well.

**Comment by luusluus** [comment]
Great. Sorry for the inconvenience
