### ISSUE TITLE
Critical Bug: Query View - Cannot view query on Windows

### ISSUE THREAD

**Issue by darrylthom** [luusluus/vscode-parquet-visualizer#145]
On Windows when I am on the Query view, I no longer see a textarea for me to edit the query in. I can see the Run/Clear buttons and the results, but no area for my SELECT statement to be entered.

This is specifically at larger screen sizes

**Comment by darrylthom** [comment]
> Darn it, I'd tested it on windows locally before hand and all seemed well.

Screen-size or viewport specific. Larger won't show it.

**Comment by luusluus** [comment]
Hmm, ok. It's a bit problematic, i'm currently away from home and only have my laptop with me. Maybe I can find the fix and you can test it with a VSIX?

**Comment by darrylthom** [comment]
> VSIX

Yes, I can do that.

**Comment by luusluus** [comment]
Does it re-appear when you make the window smaller?

**Comment by darrylthom** [comment]
> Does it re-appear when you make the window smaller?

Yes

**Comment by luusluus** [comment]
I think I've fixed it. no need to send you a vsix. new version should be uploaded soon to market place. Thanks for catching this.

**Comment by luusluus** [comment]
@darrylthom can you verify it's fixed?

**Comment by darrylthom** [comment]
We are good now, thanks!

**Comment by luusluus** [comment]
Awesome, sorry for the inconvience.

**Comment by darrylthom** [comment]
> Awesome, sorry for the inconvience.

Not at all, I like troubleshooting lol
