### ISSUE TITLE
Bug (Minor): CTRL + Enter executing even when an SQL statement is already in progress

### ISSUE THREAD

**Issue by darrylthom** [luusluus/vscode-parquet-visualizer#152]
If you spam CTRL + Enter it will give you error messages like:
Catalog Error: Table with name query_result does not exist! Did you mean "pg_enum"? LINE 3: FROM query_result ^

Should verify whether or not an SQL statement is executing similar to how the Run button disables when it is running.

**Comment by luusluus** [comment]
This should be in the latest version

**Comment by darrylthom** [comment]
Verified it is working
