### ISSUE TITLE
Bug: Query View - Search only applied to current page

### ISSUE THREAD

**Issue by darrylthom** [luusluus/vscode-parquet-visualizer#159]
Currently, the search box is only being applied to the current page. The search function should also be re-applied directly after a query is executed.

**Comment by luusluus** [comment]
Currently i reset all controls when doing a new query.

**Comment by darrylthom** [comment]
My search input box is still populated after performing a query.

**Comment by luusluus** [comment]
Ill fix this and implement search on the whole dataset/query result.

**Comment by luusluus** [comment]
In this PR I'll set the fix for resetting the search. In another PR I'll implement search on whole data set.
