### ISSUE TITLE
Extension hanging when opening parquet files

### ISSUE THREAD

**Issue by cbrueffer** [luusluus/vscode-parquet-visualizer#25]
First of all, thanks for extension, works (worked) great! 

# Description

After an extension update the other day, the extension just hangs when opening parquet files (blank tab and the progress indicator is moving, nothing changes after several minutes).

I've tried uninstalling/installing and disabling/enabling the extension multiple times, both as normal user and administrator: Other extensions seem to be running as usual.

# Environment

- parquet-visualizer 2024-07-08 22:53:29
- Windows 10
- VSCode 1.91.0

**Comment by luusluus** [comment]
Great to hear, I'll test with your file and see if I can break something.

**Comment by luusluus** [comment]
Couldn't get the extension to break with this file. So closing this issue :)
