### ISSUE TITLE
Suggest:  adjust Date type display format

### ISSUE THREAD

**Issue by homecls** [luusluus/vscode-parquet-visualizer#53]
change the format from **{Mon Sep 30 2002 08:00:00 GMT+080}**.  to  **{2002-9-30 08:00:00 Mon GMT+080}**.

**Comment by luusluus** [comment]
Thx for the suggestion.

I'll make this configurable and make your suggested format the default.

**Comment by luusluus** [comment]
You can now change the format for timestamp columns yourself. Simply edit your `settings.json` file in `.vscode` directory and add the following lines

```
"parquet-visualizer.dateTimeFormat": "YYYY-M-D HH:mm:ss ddd [GMT]Z",
"parquet-visualizer.outputDateTimeFormatInUTC": false
```
