### ISSUE TITLE
SQL stopped executing properly as of 0.11.0

### ISSUE THREAD

**Issue by darrylthom** [luusluus/vscode-parquet-visualizer#69]
Prior to 0.11.0, I could run SQL on my 600 kb Parquet file successfully. Now it hangs on "Loading..." for every query executed.

Opening the file is successful and so is viewing all of the tabs within Visual Studio. It's specifically when I run SQL.

**Comment by luusluus** [comment]
Sorry to hear this happened. Are you willing to share the parquet file for debugging?

**Comment by darrylthom** [comment]
[Sample.zip](https://github.com/user-attachments/files/17778203/Sample.zip)

**Comment by luusluus** [comment]
Thank you I'll take a look asap.

**Comment by luusluus** [comment]
I have parquet-visualizer version 0.13.1 installed on my vscode desktop installation and the querying works fine for me.

OS: Linux
Arch: x64
UI: desktop
vscode version: 1.95.3

**Comment by luusluus** [comment]
Trying 0.11.0 and the query 

```
SELECT *
FROM data
LIMIT 1000;
```

works fine as well.

**Comment by darrylthom** [comment]
Windows 10 Enterprise 64 bit
VS: 1.95.3

**Comment by luusluus** [comment]
Can you try upgrading to the latest version?

**Comment by luusluus** [comment]
I'll try to do it in a windows environment as well

**Comment by darrylthom** [comment]
Stuck on Loading for me in 0.13.1

**Comment by luusluus** [comment]
Yes! I reproduced the error. I'll come with a fix ASAP

**Comment by luusluus** [comment]
If you're stuck, you could try Windows Subsystem For Linux (WSL) on your windows machine and open vscode in a linux environment to continue your work.

**Comment by darrylthom** [comment]
Thanks! Would it also be possible with the Exporting option, to make a setting where it can prompt you where you want the file to output?

Maybe it could default to the last location you manually saved it. Right now, it is a bit unfavorable that it outputs the exports in the same folder as the parquet since we stage ours on a network share meant for production data.

**Comment by luusluus** [comment]
This should be fixed in https://github.com/luusluus/vscode-parquet-visualizer/releases/tag/v0.13.2
