### ISSUE TITLE
Query view horizontal scrollbar doesn't show unless you scroll down all the way

### ISSUE THREAD

**Issue by darrylthom** [luusluus/vscode-parquet-visualizer#70]
Currently when you have a large dataset with many columns, you have to scroll all of the way to the bottom before you see the horizontal scrollbar to be able to scroll left and right. This becomes more difficult if you have a large Page Size (500 for example).

This happens on the **Query** view only, not on the Data view. Would also be nice to be able to resize the query frame size (where you enter the query) since it takes up a lot of real estate by default.

Tested on Windows.

**Comment by luusluus** [comment]
I see what you mean. This will be my next PR

**Comment by luusluus** [comment]
> Currently when you have a large dataset with many columns, you have to scroll all of the way to the bottom before you see the horizontal scrollbar to be able to scroll left and right. This becomes more difficult if you have a large Page Size (500 for example)

This is solved.

> Would also be nice to be able to resize the query frame size (where you enter the query) since it takes up a lot of real estate by default.

I'll try to do this in next release.
