### ISSUE TITLE
Feature: Change default Page Size to 1000 and add All as an option

### ISSUE THREAD

**Issue by darrylthom** [luusluus/vscode-parquet-visualizer#78]
Maybe since the default query is:

SELECT *
FROM data
LIMIT 1000;

Perhaps it makes sense to have the default Page Size across Data and Query both be 1000? Perhaps even a last option for **All** if the end-user is comfortable with an even larger dataset being displayed.

**Comment by luusluus** [comment]
You can configure the query and the default page sizes. But I can consider of defaulting them to 1000 as starting page size.

**Comment by luusluus** [comment]
This will be my next priority. Together with sorting whole dataset.

**Comment by luusluus** [comment]
I've added all functionality to page sizes
