### ISSUE TITLE
Bug: Query View - Next Page / Last Page option available when less results than Page Size

### ISSUE THREAD

**Issue by darrylthom** [luusluus/vscode-parquet-visualizer#79]
For example, I have 800 rows of data and my page size is set to 1000. It allows me to click **Next**/Last where nothing happens.

When I click **Next** and then execute the same query again, it gets stuck on Loading.

**Comment by luusluus** [comment]
I'll fix it asap and test all pagination functionality more thoroughly.

**Comment by darrylthom** [comment]
This didn't occur in 0.10.1

**Comment by luusluus** [comment]
This is in the query tab, correct?

**Comment by darrylthom** [comment]
That is correct. Also, sorry to bombard you -- I was testing out a variety of things today and saw a few bugs and had some ideas that would improve the experience.

**Comment by luusluus** [comment]
> For example, I have 800 rows of data and my page size is set to 1000. It allows me to click Next/Last where nothing happens. When I click Next and then execute the same query again, it gets stuck on Loading.

I've reproduced the error.
When the query result is less than the **first** default page size, then indeed the next and last button are visible now and clicking on it does nothing.

**Comment by darrylthom** [comment]
Strangely enough, I also think the JSON settings file where it mentions parquet-visualizer default page sizes, it actually defaults it to the array as empty. I believe this is what I saw when I went into those settings:

"parquet-visualizer.defaultPageSizes": [

    ]

It didn't have the sizes I was actually seeing in the extension before (20/50/100/500?)

I had changed this to:

"parquet-visualizer.defaultPageSizes": [
    
    1000

    ]

To make it work again

**Comment by darrylthom** [comment]
> > For example, I have 800 rows of data and my page size is set to 1000. It allows me to click Next/Last where nothing happens. When I click Next and then execute the same query again, it gets stuck on Loading.
> 
> I've reproduced the error. When the query result is less than the **first** default page size, then indeed the next and last button are visible now and clicking on it does nothing.

Yes, and when you click Next and try executing the Query again, it seems to break it and gets stuck on Loading. Last doesn't do this. But obviously greying them both out in the first place would fix that issue as well.
