### ISSUE TITLE
Feature: Data & Query Views - Remove "T00:00:00.00.000Z" from Date32 data types

### ISSUE THREAD

**Issue by darrylthom** [luusluus/vscode-parquet-visualizer#85]
I believe that Date32 does not support time, so perhaps the views would be cleaner without the "T00:00:00.00.000Z" on the end. Especially when this gets copied and pasted into Excel, the program won't recognize the format unless I parse it out.

**Comment by luusluus** [comment]
This is now available in v0.15.0
