### ISSUE TITLE
Bug (Minor): Query View - Button sizes (Run, Clear and Copy page)

### ISSUE THREAD

**Issue by darrylthom** [luusluus/vscode-parquet-visualizer#86]
When certain conditions are met, the Run, Clear and Copy page buttons' text is showing outside its buttons borders.

This happens specifically when I have a terminal open at the bottom of VS Code, like when I just ran a Python script. The borders end up resizing depending how big my terminal window height is. Export results button is not affected.

**Comment by darrylthom** [comment]
This happens specifically when I have a terminal open at the bottom of VS Code, like when I just ran a Python script.

**Comment by luusluus** [comment]
do you have a screenshot of this happening?
And on what resolution is this happening?

**Comment by darrylthom** [comment]
![image](https://github.com/user-attachments/assets/957afd57-b268-4ef6-b3e0-15fb5245c719)

You can see the issues with the buttons on there. It's when I have an execution pane at the bottom. My laptop resolution is much smaller though, so it happens if I have a terminal open at the bottom.

**Comment by luusluus** [comment]
This is now fixed in v0.15.0
