### ISSUE TITLE
Bug: Query View - Copy Page still includes some formatting

### ISSUE THREAD

**Issue by darrylthom** [luusluus/vscode-parquet-visualizer#88]
When I use Copy, and paste into Excel it looks like it is still including the following formatting options:
-Bold
-Wrap Text (this one especially ends up not looking great in Excel)

And I am not sure if it's possible, but let's say I have a String of "001000". When I paste this, Excel automatically changes it to a number 1000. I was not sure if it's possible to flag what is being copied to the clipboard as text explicitly so that it does not lose the leading the zeroes. I know this one is sort of an Excel issue since it's automatically casting to a whole number.

**Comment by luusluus** [comment]
Do you mean that text is wrapped like the following?

![image](https://github.com/user-attachments/assets/0438a3aa-79ba-4250-8dde-348f5140ab56)

In this example I manually set wrap text to a cell. Initially it wasn't wrapped.

**Comment by darrylthom** [comment]
> Do you mean that text is wrapped like the following?
> 
> ![image](https://private-user-images.githubusercontent.com/21309426/388640704-0438a3aa-79ba-4250-8dde-348f5140ab56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMTQ2ODgsIm5iZiI6MTczMjIxNDM4OCwicGF0aCI6Ii8yMTMwOTQyNi8zODg2NDA3MDQtMDQzOGEzYWEtNzliYS00MjUwLThkZGUtMzQ4ZjUxNDBhYjU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDE4Mzk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5YWIwZDJlNDg3ZDhiMzEzYzlhOTMyY2QyODk4Y2QyODIzYmJmYzhhOTYyZjk3MzM0M2VkN2QzNTQ2MmFmNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.e8XsQpDgouTUGYUiDysi61oXiUyY_5mZuvBLInUInCQ)
> 
> In this example I manually set wrap text to a cell. Initially it wasn't wrapped.

When I use Copy Page and paste directly into Excel, all of my cells pasted in have Wrap Text selected in the Home tab and the first row has Bold text.

**Comment by darrylthom** [comment]
> Maybe in excel the underling value is still "001000" but excel decides to logically present it as 1000? I'm not sure.
> 
> I'll take a look in the options on what's possible here.
> 
> Do you have an example parquet file that I can test this on?

[number leading zeroes.zip](https://github.com/user-attachments/files/17850763/number.leading.zeroes.zip)

Here is an example of a field with leading zeroes.

**Comment by luusluus** [comment]
Thanks for the example. Do you also have a parquet file where the wrapping text occurs in excel?

**Comment by darrylthom** [comment]
> Thanks for the example. Do you also have a parquet file where the wrapping text occurs in excel?

That one with the leading zeroes is doing the text wrapping in Excel as well.

**Comment by darrylthom** [comment]
Perhaps this could solve the leading zeroes getting messed up? Assuming you are copying an HTML table...

This would be for String columns:
<td style="mso-number-format:\@;">

https://dev.to/anrodriguez/styling-excel-cells-with-mso-number-format-css-attribute-updated-j6i

**Comment by darrylthom** [comment]
For String it got cut off, but this might fi the leading zeroes issues:

`mso-number-format:"\@"`

**Comment by darrylthom** [comment]
> I don't think I'm getting the wrapping with your example parquet file. Could you make a screenshot what you mean with word wrapping?
> 
> FYI: I tested it in google sheets and I get the following:
> 
> ![image](https://private-user-images.githubusercontent.com/21309426/389061086-b40351d9-0e87-4e37-8ad3-94b95518ff7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMDcwNTIsIm5iZiI6MTczMjMwNjc1MiwicGF0aCI6Ii8yMTMwOTQyNi8zODkwNjEwODYtYjQwMzUxZDktMGU4Ny00ZTM3LThhZDMtOTRiOTU1MThmZjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDIwMTkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0Zjc0NzU4ZGQ0M2JhOWQxOTcwMjBkNzhhNzVhMGY5MDI4MmY5ODMyMGMxYjJkNjE4YTRkM2ZmNDM1ZmIyNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.c54PDwnu-jWKh_40b9Fi00OHcni1PXzJ9u5dMhODM4I)

I don't have Excel on my personal PC and cannot share screenshots from my work laptop. However, the option being enabled looks like this on every cell I pasted:

![image](https://github.com/user-attachments/assets/f789657d-ff9e-4d06-aca6-0f1bf935a39f)

The cells are being stretched out and I have to resize everything.

**Comment by luusluus** [comment]
I'm using office 365 excel for the web and I've tried to apply the following:

- `<td style="mso-number-format:\@;">`

- `th, td { white-space: nowrap; font-weight: normal; }`

The bolded headers are gone. 

The word wrap remains enabled when pasted into office 365. However, when I do `CTRL + Z` the word wrap is diabled. So it seems office 365 excel for the web does some automatic post processing based on some configuration to apply word wrap for cells that are longer than the headers.

`mso-number-format` simply doesn't seem to work. So now I try to match each cell whether they contain leading zeroes using the regex `/^0+\d+/` and then prepend a `'` for it, making it a text value. Which makes sure that the leading zeroes remain.

**Comment by darrylthom** [comment]
> I'm using office 365 excel for the web and I've tried to apply the following:
> 
> * `<td style="mso-number-format:\@;">`
> * `th, td { white-space: nowrap; font-weight: normal; }`
> 
> The bolded headers are gone.
> 
> The word wrap remains enabled when pasted into office 365. However, when I do `CTRL + Z` the word wrap is diabled. So it seems office 365 excel for the web does some automatic post processing based on some configuration to apply word wrap for cells that are longer than the headers.
> 
> `mso-number-format` simply doesn't seem to work. So now I try to match each cell whether they contain leading zeroes using the regex `/^0+\d+/` and then prepend a `'` for it, making it a text value. Which makes sure that the leading zeroes remain.
> 
> I'll try to make a pre-release on vscode, so that you can install the next version and try it with excel for desktop. See if it does work for you there.

Thanks for all of your hard work on this. I will test the word-wrap with the changes you made when you publish the update. It's possible it might still work in Desktop. With adding ' at the start, this may fix it in Excel but could potentially cause issues in other places outside of Excel. Is it possible that with your previous formatting changes, it might be stripping out the mso style?

**Comment by luusluus** [comment]
In current release I'm not doing any custom formatting on the copied result.

I'll publish the version where I'll not prepend it with a ' and only keep the excel style. So that you can test whether it works on excel desktop.

**Comment by darrylthom** [comment]
I did some testing where I actually tried to copy the HTML code itself rather than the output HTML and paste it into Excel and the mso @ tag and the no-wrap both get respected when Excel converts the HTML code into a table on the sheet.

**Comment by luusluus** [comment]
Thanks for your reply and testing. Which mso tags are you referring to for floats, dates and integers (having commas)?

Can you share your HTML code example that was respected by Excel?

**Comment by darrylthom** [comment]
This worked to fix my issues with the leading zeroes when I copied and pasted the raw HTML:

`<table>
<tr>
<td style="white-space: nowrap; mso-number-format:'\@';">000022</td>
</tr>
</table>
`

**Comment by darrylthom** [comment]
[4 examples.txt](https://github.com/user-attachments/files/17894600/4.examples.txt)

Example 1: Text
Example 2: Numeric Text
Example 3: Float
Example 4: Integer

**Comment by darrylthom** [comment]
Actually, I am wrong. I can define the classes and it works properly. Attached is a more organized example.

[4 examples.txt](https://github.com/user-attachments/files/17894663/4.examples.txt)


Pasting raw HTML works on Desktop Excel but not Web.

**Comment by luusluus** [comment]
Formatting should be improved in v0.15.0. Please let me know if there are still any issues or improvements to be made, as I can't test without having an Excel license.
